import { useEffect, useState } from 'react';
import { apiFetch } from '../utils/api';
import { CheckCircle, Eye, ArrowLeft, Printer } from 'lucide-react';

const Invoices = () => {
  const [invoices, setInvoices] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [currentUser, setCurrentUser] = useState<any>(null);

  // Detail view states
  const [selectedInvoice, setSelectedInvoice] = useState<any>(null);
  const [invoiceHtml, setInvoiceHtml] = useState<string>('');
  const [detailLoading, setDetailLoading] = useState(false);

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem('user') || '{}');
    setCurrentUser(user);

    const fetchInvoices = async () => {
      try {
        setLoading(true);
        const res = await apiFetch('/invoices');
        if (res.success && Array.isArray(res.data)) {
          // If Vendor, filter their own invoices
          if (user.role === 'Vendor') {
            setInvoices(res.data.filter((inv: any) => inv.vendor_id === user.id));
          } else {
            setInvoices(res.data);
          }
        }
      } catch (err: any) {
        console.error("Error loading invoices:", err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchInvoices();
  }, []);

  const handlePay = async (invoiceId: number, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    try {
      const res = await apiFetch(`/invoices/${invoiceId}/pay`, {
        method: 'PATCH'
      });
      if (res.success) {
        alert("Payment processed successfully!");
        setInvoices(prev => prev.map(inv => inv.id === invoiceId ? { ...inv, status: 'Paid' } : inv));
        if (selectedInvoice && selectedInvoice.id === invoiceId) {
          setSelectedInvoice({ ...selectedInvoice, status: 'Paid' });
          // Re-fetch HTML to update status badge in PDF
          handleViewInvoice({ ...selectedInvoice, status: 'Paid' });
        }
      }
    } catch (err: any) {
      alert(`Payment failed: ${err.message}`);
    }
  };

  const handleViewInvoice = async (inv: any) => {
    setSelectedInvoice(inv);
    setDetailLoading(true);
    try {
      const res = await apiFetch(`/invoices/${inv.id}/pdf`);
      if (res.success && res.pdf_html) {
        setInvoiceHtml(res.pdf_html);
      }
    } catch (err: any) {
      console.error("Failed to load invoice HTML:", err.message);
      alert("Could not load invoice details.");
      setSelectedInvoice(null);
    } finally {
      setDetailLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return <div className="p-8 text-center">Loading Invoices...</div>;
  }

  if (selectedInvoice) {
    return (
      <div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <button className="btn btn-outline" onClick={() => setSelectedInvoice(null)} style={{ padding: '0.5rem' }}>
              <ArrowLeft size={20} />
            </button>
            <div>
              <h1 style={{ margin: 0 }}>Invoice Details</h1>
              <p className="text-muted m-0">{selectedInvoice.invoice_number}</p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            {currentUser?.role === 'Procurement Officer' && selectedInvoice.status === 'Unpaid' && (
              <button className="btn btn-primary" onClick={() => handlePay(selectedInvoice.id)}>
                <CheckCircle size={18} /> Process Payment
              </button>
            )}
            <button className="btn btn-outline" onClick={handlePrint}><Printer size={18} /> Print</button>
          </div>
        </div>

        {detailLoading ? (
          <div className="card text-center p-8 text-muted">Generating Invoice View...</div>
        ) : (
          <div className="card" style={{ padding: '2rem' }}>
            <div dangerouslySetInnerHTML={{ __html: invoiceHtml }} />
          </div>
        )}
      </div>
    );
  }

  return (
    <div>
      <div style={{ marginBottom: '2rem' }}>
        <h1>Invoices</h1>
        <p className="text-muted">View and manage invoices generated by vendors</p>
      </div>

      <div className="card">
        {invoices.length === 0 ? (
          <div className="p-8 text-center text-muted">No invoices found.</div>
        ) : (
          <div className="table-container">
            <table>
              <thead>
                <tr>
                  <th>Invoice No</th>
                  <th>PO Reference</th>
                  <th>Vendor</th>
                  <th>Date Issued</th>
                  <th style={{ textAlign: 'right' }}>Total Amount</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {invoices.map((inv: any) => (
                  <tr key={inv.id} style={{ cursor: 'pointer' }} onClick={() => handleViewInvoice(inv)} className="hover-row">
                    <td className="font-bold">{inv.invoice_number}</td>
                    <td>{inv.po_number}</td>
                    <td>{inv.company_name || inv.vendor_name}</td>
                    <td>{new Date(inv.issued_at).toLocaleDateString()}</td>
                    <td style={{ textAlign: 'right' }}>${parseFloat(inv.total_amount).toFixed(2)}</td>
                    <td>
                      <span className={`badge ${inv.status === 'Paid' ? 'badge-success' : 'badge-warning'}`}>
                        {inv.status}
                      </span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', gap: '0.5rem' }}>
                        <button className="btn btn-outline btn-sm" onClick={(e) => { e.stopPropagation(); handleViewInvoice(inv); }}>
                          <Eye size={16} /> View
                        </button>
                        {currentUser?.role === 'Procurement Officer' && inv.status === 'Unpaid' && (
                          <button className="btn btn-primary btn-sm" onClick={(e) => handlePay(inv.id, e)}>
                            <CheckCircle size={16} style={{marginRight: '4px'}}/> Pay
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default Invoices;
